// A synthetic 33-task board: a family's Kyushu camping trip (the epic and
// its 18 members) plus unfiled kitchen and trip-support tasks. It began as a
// snapshot of a real work board; t-862b re-themed the SURFACE (titles,
// bodies, label/repo names, the epic title) while keeping every id, lane,
// priority, dependency, timestamp and checklist shape — the structure is
// what the demos and tests exercise, and CJK-heavy titles are the point
// (the width bugs this app guards against live there). Epics are not tasks
// and hold no lane. This is a static in-memory copy; the mock provider
// never reads or writes a real .furrow store.

package memstore

import (
	"time"

	"github.com/akira-toriyama/ridge/internal/board"
)

func ts(s string) time.Time {
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		panic(err)
	}
	return t
}

func fixtureTasks() []*board.Task {
	return []*board.Task{
		{
			ID:       "t-jv3j",
			Title:    "行程表 v2 — 阿蘇→高千穂を買い出しと温泉の寄り道込みで引き直す（雨天代替つき）",
			Status:   "backlog",
			Priority: 580,
			Value:    3,
			Effort:   2,
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Deps:     []string{"t-ehk7", "t-t38k"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T15:47:40Z"),
			// The four Due values in this fixture are NOT from the snapshot
			// (the real board had none in 2026-07); they exist so the table's
			// due column and `-demo sort` have dates to show. Each is furrow's
			// bare-day form: the last second of that local (JST) day, in UTC.
			Due:  ts("2026-07-31T14:59:59Z"),
			Body: "# 行程表 v2\n\n初版は移動時間だけで組んでいて、買い出しと温泉が全部「ついで」扱いになっていた。[[t-ehk7]] の献立が決まり [[t-t38k]] でベースキャンプが確定したので、寄り道を主役にして引き直す。\n\n- 1日目: 出発 6:30 → 道の駅で昼と1日目夕食の生鮮 → 設営 15:00 まで\n- 2日目: 午前は川、午後は高千穂へ。霧が出たら [[t-px9p]] の屋内代替に切替\n- 3日目: 撤収 10:00 → 家族風呂（受付 14:00 まで・[[t-2qyb]] で確認済み）→ 帰路\n\n判断の軸: 子どもの昼寝時間を移動に重ねる。買い出しは1日1回まで。到着後の設営は明るいうちに終える。雨天代替は「行かない」も選択肢に含める（無理に埋めない）。",
		},
		{
			ID:       "t-2qyb",
			Title:    "立ち寄り温泉の下調べ — 家族風呂の有無と受付終了時刻を電話で確認",
			Status:   "done",
			Priority: 2380,
			Labels:   []string{"onsen"},
			Repos:    []string{"tomo/kyushu-trip"},
			Created:  ts("2026-07-17T11:35:43Z"),
			Updated:  ts("2026-07-17T13:57:21Z"),
			Closed:   ts("2026-07-17T13:57:21Z"),
			Body:     "# 立ち寄り温泉の下調べ\n\n候補3軒に電話で確認した。サイトの情報は古く、1軒は家族風呂を廃止済みだった。\n\n- ○ 山鹿の湯: 家族風呂あり・受付 14:00 まで・タオル販売あり\n- × 川沿いの湯: 家族風呂廃止（2025年）\n- ○ 高原温泉: 家族風呂あり・受付 16:00 まで・混雑は昼過ぎ\n\n結論: 3日目の帰路は山鹿の湯に寄る。受付 14:00 がタイムリミットなので撤収は 10:00 厳守（[[t-jv3j]] の行程に反映済み）。",
		},
		{
			ID:       "t-2tbn",
			Title:    "装備の棚卸し — テント・タープ・寝袋を全部出して状態を確認",
			Status:   "done",
			Priority: 1610,
			Value:    3,
			Effort:   2,
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Created:  ts("2026-07-16T08:35:53Z"),
			Updated:  ts("2026-07-16T09:26:59Z"),
			Closed:   ts("2026-07-16T09:26:59Z"),
			Body:     "# 装備の棚卸し\n\n2年ぶりに全部出した。テントはポール1本に曲がり、タープの張り綱が2本足りない。寝袋は湿気の匂いがするので洗濯行き（[[t-e5hq]]）。\n\n- テント: ポール修理キットで対応可。フライのシームテープは無事\n- タープ: 張り綱2本と自在を買い足し\n- 寝袋: 洗濯 + 撥水回復へ\n- ランタン: 電池式は生きている。マントルの予備が無い\n\n買い足しは [[t-pk4f]] の買い出し計画に合流させる。",
		},
		{
			ID:       "t-9sa6",
			Title:    "持ち物リスト最終版 — 車載レイアウトと重量配分を決めて積載図に落とす",
			Status:   "backlog",
			Priority: 660,
			Value:    4,
			Effort:   4,
			Labels:   []string{"bbq"},
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Checklist: []board.ChecklistItem{
				{Text: "カテゴリ分け — 寝る・食う・座る・火・雨・子ども", Done: false},
				{Text: "重量の実測 — 体重計で箱ごとに量る", Done: false},
				{Text: "車載レイアウト案を2つ描く（ルーフ無し前提）", Done: false},
				{Text: "降ろす順 = 設営順になるよう並べ替え", Done: false},
				{Text: "忘れ物チェック欄を印刷して玄関に貼る", Done: false},
				{Text: "積載図を清書して車のダッシュボードに入れる", Done: false},
			},
			Created: ts("2026-07-16T15:27:16Z"),
			Updated: ts("2026-07-16T15:27:16Z"),
			Due:     ts("2026-09-30T14:59:59Z"), // see t-jv3j's Due note
			Body:    "# 持ち物リスト最終版\n\nリスト自体は前回の使い回しで 8 割できている。今回の本題は積載で、後部座席に子どもが2人いる状態でルーフボックス無しに収めるのが制約。重いものを下・低頻度を奥・雨で最初に要るもの（タープ・レイン）を最後に積む。\n\n積載図はA4一枚。設営順と逆順に積むと現地で上から順に降ろせる。",
		},
		{
			ID:       "t-7wdg",
			Title:    "サイト設営図 — タープ連結と BBQ の風向きを区画図に描き込む",
			Status:   "backlog",
			Priority: 680,
			Value:    3,
			Effort:   2,
			Labels:   []string{"bbq"},
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Checklist: []board.ChecklistItem{
				{Text: "区画の寸法をキャンプ場に確認（デッキの高さ含む）", Done: false},
				{Text: "タープ連結の張り方を庭で1回リハーサル", Done: false},
				{Text: "焚き火位置と薪置き場を図に描き込む", Done: false},
			},
			Created: ts("2026-07-16T15:27:16Z"),
			Updated: ts("2026-07-16T15:27:16Z"),
			Body:    "# サイト設営図\n\n予約した区画（[[t-t38k]]）はデッキ付きで、デッキ側にテントを置くとタープの張り出しが道側になる。夕方の谷風が川下からくるので、焚き火はデッキの風下・タープの外に出す。",
		},
		{
			ID:       "t-ehk7",
			Title:    "キャンプ献立プラン — 3泊分の夕食を現地調達と常備菜持参で組む（買い出しリスト付き）",
			Status:   "backlog",
			Priority: 570,
			Value:    5,
			Effort:   4,
			Labels:   []string{"bento"},
			Repos:    []string{"tomo/joubisai", "tomo/kyushu-trip"},
			Checklist: []board.ChecklistItem{
				{Text: "3泊分の夕食を骨組みだけ決める", Done: false},
				{Text: "常備菜から持っていく品を回転表と突き合わせる", Done: false},
				{Text: "店別の買い出しリストに分解する", Done: false},
				{Text: "丸鶏の受け取り予約を道の駅に電話", Done: false},
				{Text: "ホットサンドの仕込み手順を前夜分に書き出す", Done: false},
				{Text: "子ども向けの別枠（とうもろこし・マシュマロ）を確保", Done: false},
				{Text: "保冷の詰め順をクーラー割りと突き合わせる", Done: false},
			},
			Created: ts("2026-07-16T15:47:39Z"),
			Updated: ts("2026-07-16T15:47:39Z"),
			Due:     ts("2026-08-20T14:59:59Z"), // see t-jv3j's Due note
			Body:    "# キャンプ献立プラン\n\n方針: 初日は移動で疲れているので火を使う品を1品に絞る。2日目の夜が本番（ダッチオーブン）。3日目は残り物を使い切って撤収を軽くする。常備菜（[[t-phgp]] の回転から抜く分）を保冷の底に敷いて、現地調達は生鮮だけにする。\n\n- 1日目夜: 焼くだけの肉 + 持参の常備菜2品 + 汁物\n- 2日目朝: ホットサンド（前夜に仕込み）\n- 2日目夜: ダッチオーブンの丸鶏 + 道の駅の野菜\n- 3日目朝: 残り野菜の雑炊\n- 昼はすべて行程側（[[t-jv3j]]）の道の駅で現地判断\n\n買い出しリストは店別に分ける: 出発前（乾物・調味料・常備菜の補充）/ 道の駅1（初日の生鮮）/ 道の駅2（丸鶏の受け取り予約 — 電話済み、当日 10-14 時受取）。\n\n保冷の制約: クーラーは2台体制（[[t-9m2q]]）で、生鮮は開閉の少ない方へ。氷の持ちは [[t-614w]] の実測で3日目まで足りる見込みだが、丸鶏だけは受け取りを2日目にして冷蔵時間を最短化する。\n\n子どもの好き嫌い対応: 丸鶏の付け合わせに素焼きのとうもろこしを別枠で確保。デザートはマシュマロ（焚き火の火起こし練習 [[t-fn4k]] とセットで本人たちに焼かせる）。",
		},
		{
			ID:       "t-9m2q",
			Title:    "クーラー2台の中身割り — 生鮮と飲料を分けて開閉頻度を下げる",
			Status:   "backlog",
			Priority: 605,
			Value:    3,
			Effort:   3,
			Labels:   []string{"bbq"},
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Deps:     []string{"t-614w"},
			Created:  ts("2026-07-17T06:58:54Z"),
			Updated:  ts("2026-07-17T15:04:56Z"),
			Body:     "# クーラー2台の中身割り\n\n氷持ち実測（[[t-614w]]）の結論は「開閉が全て」。飲料用は何度開けてもいい前提で氷多め、生鮮用は1日2回しか開けない運用にする。\n\n- 生鮮用: 肉・乳製品・仕込み済みの常備菜。朝と夕方のみ開ける\n- 飲料用: 麦茶・ジュース・ビール。氷は袋のまま上に載せる\n- 保冷剤は生鮮用に全振り。飲料用は溶けたら道の駅で袋氷を買い足す\n\n積む位置も分ける: 生鮮用は荷室の奥（走行中に開けない）、飲料用は後席の足元。",
		},
		{
			ID:       "t-phgp",
			Title:    "常備菜の回転表 v1 — 平日5日を3品で回す型を作る",
			Status:   "done",
			Priority: 1620,
			Value:    4,
			Effort:   2,
			Repos:    []string{"tomo/joubisai"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T11:26:43Z"),
			Closed:   ts("2026-07-16T11:14:01Z"),
			Body:     "# 常備菜の回転表 v1\n\n週末に3品仕込んで平日5日を回す型ができた。日曜の仕込みは90分以内、材料は1回の買い物で揃える、を制約にする。\n\n- 月火: 品A + 卵で1品足す\n- 水木: 品B + 焼くだけの主菜\n- 金: 品Cを使い切る + 冷凍の予備\n\n3週回して破綻しなかったので v1 として固定。飽き対策の拡張は [[t-m4kz]] へ。",
		},
		{
			ID:       "t-pk4f",
			Title:    "買い出し計画 — 行程の道の駅ごとに買う物を割り振る",
			Status:   "backlog",
			Priority: 690,
			Value:    2,
			Effort:   3,
			Labels:   []string{"bbq"},
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Deps:     []string{"t-jv3j"},
			Created:  ts("2026-07-16T15:27:16Z"),
			Updated:  ts("2026-07-16T15:27:16Z"),
			Body:     "# 買い出し計画\n\n行程表（[[t-jv3j]]）の停車地が決まらないと割り振れないので待ち。決まり次第、献立の店別リスト（[[t-ehk7]]）を停車順に並べ替えて、冷蔵品が車内に滞在する時間を最短にする。氷の買い足しポイントもここで決める。",
		},
		{
			ID:       "t-g8bn",
			Title:    "車の12ヶ月点検とタイヤ交換見積 — 霧の高千穂の山道に備える",
			Status:   "done",
			Priority: 1610,
			Value:    4,
			Effort:   3,
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Deps:     []string{"t-6etg"},
			Checklist: []board.ChecklistItem{
				{Text: "点検予約と代車の手配", Done: true},
			},
			Created: ts("2026-07-16T08:35:53Z"),
			Updated: ts("2026-07-16T12:59:05Z"),
			Closed:  ts("2026-07-16T12:59:05Z"),
			Body:    "# 車の12ヶ月点検とタイヤ交換見積\n\n候補調査（[[t-6etg]]）で霧の山道が確定したので点検を前倒しした。ブレーキパッド残 4mm で交換推奨 → 実施した。タイヤは山残り 3.5mm、今回は保たせて秋に交換の見積だけ取得。ワイパーは助手席側がビビるので交換済み。霧灯の球切れも発見 → 交換。",
		},
		{
			ID:       "t-ecfm",
			Title:    "ダッチオーブンの手入れ — シーズニングをやり直して蓋の噛みを直す",
			Status:   "done",
			Priority: 1630,
			Value:    3,
			Effort:   1,
			Repos:    []string{"tomo/joubisai"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T11:26:43Z"),
			Closed:   ts("2026-07-16T11:25:37Z"),
			Body:     "# ダッチオーブンの手入れ\n\n半年放置で薄錆。金束子で落としてから空焼き→油→冷却を3周（いわゆる dutch-oven の再シーズニング）。蓋の噛みは縁の錆が原因で、落としたらスッと閉まるようになった。次回から使用後は完全乾燥＋薄油を守る。",
		},
		{
			ID:       "t-rmtc",
			Title:    "予約の総ざらい — 温泉・レンタル品・雨天予備日をまとめて確定する",
			Status:   "backlog",
			Priority: 670,
			Value:    5,
			Effort:   4,
			Labels:   []string{"bbq"},
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Deps:     []string{"t-jv3j"},
			Checklist: []board.ChecklistItem{
				{Text: "家族風呂の時間指定（山鹿の湯）", Done: false},
				{Text: "焚き火用の薪とコット2台のレンタル予約", Done: false},
				{Text: "雨天予備日のキャンセル期限を確認して表に書く", Done: false},
				{Text: "予約一覧を印刷して行程表の裏に貼る", Done: false},
			},
			Created: ts("2026-07-16T15:27:16Z"),
			Updated: ts("2026-07-16T15:27:16Z"),
			Body:    "# 予約の総ざらい\n\n行程（[[t-jv3j]]）が引き直されたら、散らばっている予約を一気に確定する。個別に取ると変更時に漏れるので、一覧表 + 変更期限の列で管理する。",
		},
		{
			ID:       "t-614w",
			Title:    "クーラーの氷持ち実測 — 温泉待ちと焚き火の熱を織り込んで3日運用を決める",
			Status:   "done",
			Priority: 515,
			Value:    4,
			Effort:   2,
			Labels:   []string{"bbq"},
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Deps:     []string{"t-2qyb", "t-wf4p"},
			Created:  ts("2026-07-17T06:58:54Z"),
			Updated:  ts("2026-07-17T14:06:15Z"),
			Closed:   ts("2026-07-17T14:06:15Z"),
			Body:     "# クーラーの氷持ち実測\n\nベランダで3日間の実測をした。結論: 板氷2枚 + 保冷剤で、開閉を朝夕に絞れば3日目の朝まで 5℃ 以下を維持できる。袋氷は溶けが早く、飲料用の使い捨てと割り切る。\n\n- 実測: 外気 32℃ 日陰。1日目 2℃ / 2日目 4℃ / 3日目朝 5℃\n- 開閉を自由にした比較側は2日目夕方に 9℃ まで上がった\n- 事前予冷（前夜から氷1枚）で立ち上がりが 3℃ 変わる\n\nこの結果を [[t-9m2q]] の2台割りの前提にする。焚き火台（[[t-wf4p]]）の風下に置くと輻射で溶けが早まるのも比較で分かったので、設置図では日陰の風上に固定する。温泉の待ち時間（[[t-2qyb]]）の車内放置が最大のリスクなので、3日目は生鮮を使い切ってから温泉に寄る順にする。",
		},
		{
			ID:       "t-px9p",
			Title:    "雨天プラン — 高千穂が霧で沈んだ日の屋内代替を並べる",
			Status:   "backlog",
			Priority: 630,
			Value:    3,
			Effort:   3,
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Deps:     []string{"t-r7wr"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T15:28:28Z"),
			Body:     "# 雨天プラン\n\n高千穂は霧が出ると峡谷も星も全滅する。遊び計画（[[t-r7wr]]）の屋外項目それぞれに屋内の差し替え先を対応させておく。資料館・酒蔵見学・室内プールの3候補を距離順に並べ、当日朝の判断だけで切り替えられる形にする。",
		},
		{
			ID:       "t-0esb",
			Title:    "子どもの自由研究連動 — 火起こしと星の観察記録の段取りを作る",
			Status:   "backlog",
			Priority: 620,
			Value:    5,
			Effort:   4,
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Deps:     []string{"t-fn4k", "t-t38k"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T15:26:21Z"),
			Body:     "# 子どもの自由研究連動\n\nせっかくなので夏休みの自由研究をキャンプに乗せる。火起こし（安全講習 [[t-fn4k]] の練習と接続）と星の観察（ベースキャンプ [[t-t38k]] は光害が少ない）の2本立て。記録用紙を先に作っておかないと現地で書かないので、観察ノートの型を印刷して持っていく。",
		},
		{
			ID:       "t-6etg",
			Title:    "キャンプ場の候補調査 — 阿蘇周辺5箇所を設備と直火可否で比較",
			Status:   "done",
			Priority: 1600,
			Value:    4,
			Effort:   3,
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Deps:     []string{"t-2tbn"},
			Created:  ts("2026-07-16T08:35:53Z"),
			Updated:  ts("2026-07-16T10:27:36Z"),
			Closed:   ts("2026-07-16T10:27:36Z"),
			Body:     "# キャンプ場の候補調査\n\n阿蘇周辺5箇所を比較した。軸は: 直火可否 / デッキやサイトの水はけ / 炊事場の湯 / 子連れ動線（トイレまでの距離）/ 星の見え方。\n\n- A: 直火可・炊事場に湯なし・トイレ遠い\n- B: 焚き火台のみ・デッキ付き区画あり・湯あり・トイレ近い ← 本命\n- C: 直火可だが川増水時に閉鎖歴\n- D: 高規格すぎて空きなし\n- E: 星は最高・設備は最低\n\nB を第一候補として装備の前提（[[t-2tbn]]）を焚き火台前提に更新。予約は [[t-t38k]]。",
		},
		{
			ID:       "t-n2fc",
			Title:    "出発前夜の段取り — 積み込み順と朝の動線を分単位で書き出す",
			Status:   "ready",
			Priority: 560,
			Value:    4,
			Effort:   3,
			Labels:   []string{"bbq"},
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Created:  ts("2026-07-16T14:17:29Z"),
			Updated:  ts("2026-07-17T15:04:56Z"),
			Body:     "# 出発前夜の段取り\n\n6:30 出発を成立させるには前夜の積み込みで 9 割決まる。前回は朝にクーラーの予冷を忘れて出発が 40 分遅れたので、前夜やることと朝しかできないことを分けて壁に貼る。\n\n## 前夜（21:00 まで）\n\n- 常温の荷物を積載図（[[t-9sa6]]）どおりに積み切る\n- クーラー2台に氷1枚ずつ入れて予冷開始（[[t-614w]] の実測より、予冷の有無で立ち上がりが 3℃ 違う）\n- 子どもの着替えと朝食を玄関にまとめる\n- 車の燃料を満タンにしておく（朝のスタンド寄りをなくす）\n- 焚き火道具とレインは最後に積む位置を空けておく\n\n## 朝（5:45 起床 → 6:30 発）\n\n- 5:45 大人起床・湯を沸かす\n- 6:00 生鮮と常備菜をクーラーへ（予冷氷は入れ替えない）\n- 6:10 子ども起床・着替え・トイレ\n- 6:20 最終チェック欄（玄関の貼り紙）を上から消す\n- 6:30 発。朝食は車内でホットサンド（前夜仕込み [[t-ehk7]]）\n\n## 判断メモ\n\n- 出発が 7:00 を過ぎたら1日目の温泉を諦めて設営を優先する（行程 [[t-jv3j]] の分岐）\n- 忘れ物に気づいても 30 分以内に戻れないなら現地調達に切り替える\n- 雨予報が出発時点で 80% を超えていたら、初日の外遊びを [[t-px9p]] の屋内案に差し替える\n\n分単位の表は冷蔵庫用と車のダッシュボード用の2部を印刷する。前回はスマホの中にあって誰も見なかった。",
		},
		{
			ID:       "t-7mcc",
			Title:    "グループサイト化の検討 — 友人家族と合流する場合の区画と食事分担",
			Status:   "backlog",
			Priority: 700,
			Value:    3,
			Effort:   4,
			Labels:   []string{"bbq"},
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Created:  ts("2026-07-16T15:27:16Z"),
			Updated:  ts("2026-07-16T15:27:16Z"),
			Body:     "# グループサイト化の検討\n\n友人家族が2日目から合流するかもしれない。合流するなら隣接区画を追加で押さえ、夕食の分担（うちが主菜・先方が副菜と米）を決める。確定は出発2週間前まで。",
		},
		{
			ID:       "t-fn4k",
			Title:    "装備の安全講習 — ナイフと火の扱いを子どもと練習する",
			Status:   "backlog",
			Priority: 610,
			Value:    4,
			Effort:   3,
			Labels:   []string{"gear"},
			Repos:    []string{"tomo/kyushu-trip"},
			Checklist: []board.ChecklistItem{
				{Text: "ナイフの受け渡しと持ち方（座って・鞘に戻すまで）", Done: false},
				{Text: "フェザースティック作りを1本最後まで", Done: false},
				{Text: "火起こしをメタルマッチで（マシュマロで釣る）", Done: false},
				{Text: "火の半径ルールをテープを張って体で覚える", Done: false},
				{Text: "革手袋のサイズ確認と買い足し", Done: false},
				{Text: "約束事3つを紙に書いて本人がサインする", Done: false},
			},
			Created: ts("2026-07-16T15:25:44Z"),
			Updated: ts("2026-07-17T02:04:09Z"),
			Body:    "# 装備の安全講習\n\n現地でいきなりやらせると危ないので、庭で2回練習してから行く。約束事は3つだけにする: 刃物は座って使う・火の半径1mに走って入らない・軍手ではなく革手袋。",
		},
		{
			ID:       "t-r7wr",
			Title:    "現地の遊び計画 — 川遊びと星見の装備・安全ルールを決める",
			Status:   "backlog",
			Priority: 600,
			Value:    4,
			Effort:   4,
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Deps:     []string{"t-t38k", "t-wf4p"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T15:47:40Z"),
			Body:     "# 現地の遊び計画\n\n川遊びはベースキャンプ（[[t-t38k]]）から徒歩5分の浅瀬。増水時の判断基準（前日夜の雨量）とライフジャケット常時着用をルール化する。星見は焚き火台（[[t-wf4p]]）を消してから 30 分待つと目が慣れる。観察の道具立ては [[t-b2rf]] の予習に合わせる。",
		},
		{
			ID:       "t-f6c3",
			Title:    "キャンセル規定の整理 — 台風時の判断期限をカレンダーに落とす",
			Status:   "backlog",
			Priority: 640,
			Value:    3,
			Effort:   2,
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Deps:     []string{"t-t38k"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T15:28:28Z"),
			Body:     "# キャンセル規定の整理\n\n8月末の九州は台風が現実的なリスク。キャンプ場（[[t-t38k]]）は3日前まで無料、レンタル品は前日 17 時まで、温泉の時間指定は当日朝まで。判断期限を家族カレンダーに登録して、期限ごとに「進む/延期/中止」を決める運用にする。",
		},
		{
			ID:       "t-wf4p",
			Title:    "焚き火台の選定 — 候補3台を借りて実際に焼いて決めた",
			Status:   "done",
			Priority: 515,
			Value:    4,
			Effort:   3,
			Labels:   []string{"bbq"},
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Checklist: []board.ChecklistItem{
				{Text: "候補3台のレンタル手配", Done: true},
				{Text: "同じ食材（肉・とうもろこし）で焼き比べ", Done: true},
				{Text: "撤収と灰の始末を時間計測", Done: true},
				{Text: "決定と購入・収納場所の確保", Done: true},
			},
			Created: ts("2026-07-16T15:47:40Z"),
			Updated: ts("2026-07-17T10:38:17Z"),
			Closed:  ts("2026-07-17T10:38:17Z"),
			Body:    "# 焚き火台の選定\n\nカタログで悩むのをやめて、レンタルで3台を実際に使い比べた。評価軸は: 設営撤収の速さ / 網の高さ調整 / 灰の始末 / 車載サイズ。\n\n結論: 折りたたみの浅型に決定。設営 1 分・灰捨てが袋ごとで済むのが決め手。深型は火持ちは良いが子どもの手が届きにくく、調理向きではなかった。",
		},
		{
			ID:       "t-t38k",
			Title:    "決行判定と BBQ サイト予約 — 道具・車・食がそろったので阿蘇2泊を確定（デッキ付き A-7）",
			Status:   "done",
			Priority: 1620,
			Value:    5,
			Effort:   4,
			Repos:    []string{"tomo/kyushu-trip"},
			Epic:     "e-fw2m",
			Deps:     []string{"t-ecfm", "t-g8bn", "t-phgp"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T14:48:11Z"),
			Closed:   ts("2026-07-16T14:48:11Z"),
			Body:     "# 決行判定と BBQ サイト予約\n\n決行の条件は「道具・車・食の3点がそろうこと」と決めていた。ダッチオーブンの復活（[[t-ecfm]]）、車の点検（[[t-g8bn]]）、常備菜の回転が家で回っている実績（[[t-phgp]] — 現地の食事プランはこの延長で組める）がそろったので、候補調査の本命 B キャンプ場（[[t-6etg]]）に電話して2泊を確定した。\n\n- 予約: 8/29-31 デッキ付き A-7 区画（BBQ サイト・直火不可。焚き火台は選定済みの浅型 [[t-wf4p]] で可）\n- チェックイン 13 時 / アウト 11 時・車の乗り入れ可・支払いは現地の現金のみ\n- 増水時は川側の遊歩道が閉鎖される — 遊び計画（[[t-r7wr]]）の代替に注意\n- 薪は場内売店が 18 時まで。買い出し計画（[[t-pk4f]]）に依存しない",
		},
		{
			ID:       "t-kv82",
			Title:    "梅シロップの瓶詰め — 完成分を小瓶に移して冷蔵庫の場所を空ける",
			Status:   "in-progress",
			Priority: 3000,
			Value:    2,
			Effort:   1,
			Labels:   []string{"bento"},
			Repos:    []string{"tomo/joubisai"},
			Created:  ts("2026-08-02T09:10:00Z"),
			Updated:  ts("2026-08-09T10:05:00Z"),
			Body:     "# 梅シロップの瓶詰め\n\n6月に漬けた分が上がった。大瓶のままだと冷蔵庫を占領するので、消毒した小瓶3本に分けて1本は実家行き。梅の実は別容器で回収して、ゼリーにするか検討中。",
		},
		{
			ID:       "t-w3np",
			Title:    "味噌の天地返し — 表面のカビを取ってから塩蓋をやり直す",
			Status:   "in-progress",
			Priority: 3010,
			Value:    3,
			Effort:   2,
			Labels:   []string{"bento"},
			Repos:    []string{"tomo/joubisai"},
			Created:  ts("2026-08-03T11:00:00Z"),
			Updated:  ts("2026-08-09T11:20:00Z"),
			Body:     "# 味噌の天地返し\n\n3月仕込み分の様子見。縁に白カビが少し出ているが産膜酵母の範囲。表面 1cm を外して天地返しし、塩を薄く振り直してラップを密着させる。次の確認は10月。",
		},
		{
			ID:       "t-c9dm",
			Title:    "スパイスボックスの詰め替え — 使い切り小分けで現地の塩胡椒問題を消す",
			Status:   "in-progress",
			Priority: 3020,
			Value:    2,
			Effort:   1,
			Labels:   []string{"gear"},
			Repos:    []string{"tomo/kyushu-trip"},
			Created:  ts("2026-08-05T08:30:00Z"),
			Updated:  ts("2026-08-09T09:00:00Z"),
			Body:     "# スパイスボックスの詰め替え\n\n前回は塩胡椒を家の大瓶ごと持って行って湿気らせた。100均の小瓶で使い切りサイズに小分けし、油とめんつゆはナルゲンの小ボトルへ。箱ごと積載図の「食う」カテゴリに入れる。",
		},
		{
			ID:       "t-e5hq",
			Title:    "寝袋の洗濯と撥水回復 — 乾燥まで3日かかるので前倒しで回す",
			Status:   "in-progress",
			Priority: 3030,
			Value:    3,
			Effort:   2,
			Labels:   []string{"gear"},
			Repos:    []string{"tomo/kyushu-trip"},
			Created:  ts("2026-08-06T07:45:00Z"),
			Updated:  ts("2026-08-09T08:10:00Z"),
			Body:     "# 寝袋の洗濯と撥水回復\n\n棚卸し（[[t-2tbn]]）で湿気の匂いが出ていた2本。中性洗剤で押し洗い→浴室乾燥→ロフトが戻ってから撥水スプレー。完全乾燥まで3日見込むので出発1週間前までに終える。",
		},
		{
			ID:       "t-m4kz",
			Title:    "常備菜ローテ拡張 — 秋の根菜3品を試作してレパートリーに足す",
			Status:   "backlog",
			Priority: 710,
			Value:    3,
			Effort:   2,
			Labels:   []string{"bento"},
			Repos:    []string{"tomo/joubisai"},
			Created:  ts("2026-08-07T12:00:00Z"),
			Updated:  ts("2026-08-09T12:30:00Z"),
			Body:     "# 常備菜ローテ拡張\n\n回転表 v1（[[t-phgp]]）が夏メニューに寄っているので、秋に向けて根菜3品（きんぴら・煮浸し・南蛮）を試作する。子どもの反応を見て2品を正式採用、1品は弁当専用に回す。",
		},
		{
			ID:       "t-p7xw",
			Title:    "ポータブル電源の容量計画 — 冷蔵ボックス連続稼働を実測して決める",
			Status:   "backlog",
			Priority: 720,
			Value:    4,
			Effort:   2,
			Labels:   []string{"gear"},
			Repos:    []string{"tomo/kyushu-trip"},
			Due:      ts("2026-08-25T14:59:59Z"),
			Created:  ts("2026-08-07T13:00:00Z"),
			Updated:  ts("2026-08-09T13:15:00Z"),
			Body:     "# ポータブル電源の容量計画\n\n2日目の丸鶏（[[t-ehk7]]）まで冷蔵ボックスを保たせたい。手持ちの電源で連続稼働を実測し、足りなければレンタルの大容量を予約一覧（[[t-rmtc]]）に足す。ソーラーパネルは今回見送り。",
		},
		{
			ID:       "t-b2rf",
			Title:    "星見の予習 — 観察アプリの使い方と観察ノートの型を作る",
			Status:   "backlog",
			Priority: 730,
			Value:    2,
			Effort:   1,
			Repos:    []string{"tomo/kyushu-trip"},
			Created:  ts("2026-08-08T10:00:00Z"),
			Updated:  ts("2026-08-09T10:30:00Z"),
			Body:     "# 星見の予習\n\nベースキャンプは光害が少ない（[[t-t38k]]）。当日にアプリの使い方を覚え始めると子どもが飽きるので、ベランダで1回予習する。観察ノートの型は自由研究（[[t-0esb]]）と共用。",
		},
		{
			ID:       "t-h6vc",
			Title:    "非常食と救急セットの更新 — 期限切れを入れ替える",
			Status:   "backlog",
			Priority: 740,
			Value:    3,
			Effort:   1,
			Repos:    []string{"tomo/kyushu-trip"},
			Checklist: []board.ChecklistItem{
				{Text: "非常食の期限を全部確認して一覧化"},
				{Text: "絆創膏・ポイズンリムーバー・虫刺され薬の補充"},
				{Text: "子どもの解熱剤を薬局で相談して追加"},
			},
			Created: ts("2026-08-08T11:00:00Z"),
			Updated: ts("2026-08-09T11:45:00Z"),
			Body:    "# 非常食と救急セットの更新\n\n車載の非常食が去年の夏で止まっている。キャンプ持参分と車の常備分をまとめて入れ替える。救急セットは山用に虫刺され対応を厚めにする。",
		},
		{
			ID:       "t-y4st",
			Title:    "冬キャンプ構想 — 薪ストーブ導入の下調べ",
			Status:   "icebox",
			Priority: 5000,
			Value:    2,
			Effort:   3,
			Repos:    []string{"tomo/kyushu-trip"},
			Created:  ts("2026-08-08T12:00:00Z"),
			Updated:  ts("2026-08-09T12:10:00Z"),
			Body:     "# 冬キャンプ構想\n\n今回の旅が回ったら考える。薪ストーブはテントの幕質と煙突ポートの有無から。結露と一酸化炭素の対策を先に調べる。",
		},
		{
			ID:       "t-q8dn",
			Title:    "燻製チャレンジ — ベランダの煙対策を調べてから",
			Status:   "icebox",
			Priority: 5010,
			Value:    2,
			Effort:   3,
			Repos:    []string{"tomo/joubisai"},
			Created:  ts("2026-08-08T13:00:00Z"),
			Updated:  ts("2026-08-09T13:05:00Z"),
			Body:     "# 燻製チャレンジ\n\nダッチオーブン（[[t-ecfm]]）で温燻ができるらしい。ただしベランダの煙は近所問題になるので、熱源と煙の少ないチップの組合せを調べてから。キャンプ場でやる案が先かもしれない。",
		},
	}
}

// fixtureEpics mirrors `furrow epic ls --json` for the snapshot: the one box
// the 18 member tasks point at. Done/Total agree with the member lanes above.
func fixtureEpics() []board.EpicInfo {
	return []board.EpicInfo{{
		ID:    "e-fw2m",
		Title: "九州キャンプ旅 2026 — 行程・予約・装備（阿蘇→高千穂 3泊）",
		Done:  6,
		Total: 18,
	}}
}
