// Code generated from the real furrow board — DO NOT EDIT BY HAND.
// Source: 24 tasks from akira-toriyama/projects (the "vista" epic t-fw2m, its
// children, and their dependency targets). Bodies are the real body files,
// truncated. This is a static in-memory copy: the POC never reads or writes a
// real .furrow store.

package main

import "time"

func ts(s string) time.Time {
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		panic(err)
	}
	return t
}

// fixtureTasks is the mock board's contents.
func fixtureTasks() []*Task {
	return []*Task{
		{
			ID:       "t-jv3j",
			Title:    "vista: filter bar — typed query 構文（repo:/label:/lane:/自由語）",
			Status:   "backlog",
			Priority: 580,
			Value:    3,
			Effort:   2,
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Deps:     []string{"t-ehk7", "t-t38k"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T15:47:40Z"),
			Body:     "# vista: filter bar — typed query 構文（repo:/label:/lane:/自由語）\n\nGitHub Projects 式の単一フィルタバー。`repo:owner/name label:x lane:ready 自由語` を parse して furrow の `-r/-l/-s`/`search` に写像。全ビュー（Board/List/Graph）で共有。filter（絞る）と display options（見せ方）は概念分離（Linear）。\n\n2026-07-17 設計論点と提案（GH 機能インベントリ調査より）。ユーザーの質問「filter は furrow の機能？」への整理:\n- furrow CLI が持つのは **-r/-l/-s の等値フィルタ + search（全文）**のみ。GH 風の否定（-）・カンマ OR・no:/has:・範囲（value:>3）は furrow に無い。\n- vista は全 task を ls --json で Query cache に持つ（1 データセット + 保存ビュー模型）ので、**filter は UI 層で dataset に適用する提案**（= 見せ方の問題であり、正本ロジックの複製ではない。furrow に query 構文を足すのは CLI の flag 哲学に合わず、PR するほどの不足ではないという整理）。→ ユーザー確認待ち。\n- 構文は **GH 互換のサブセット**から始める: `repo:` `label:` `lane:`（status: を alias に）+ 自由語（単語先頭一致・GH 同）+ `-` 否定 + カンマ OR + `no:label` / `has:parent`。数値範囲・ワイルドカードは後続拡張（parser を GH 構文のサブセットとして設計しておく）。\n- filter（絞る）と display options（見せ方）の概念分離は維持（Linear）。保存ビュー（t-rmtc）の一部として view に保存される。\n- parser は fast-check の roundtrip プロパティ対象（t-v5xg）。GH filter 仕様全文: https://docs.github.com/en/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/filtering-projects\n\n2026-07-17 決定: filter の正本は furrow 側に置く（新設 -q typed query、判断規範 =「TUI を作ったらロジック冗長になるか」）。**本タスクは再スコープ**: vista 側は ①filter bar UI（入力・ハイライト・サジェスト: board 語彙/label/repo 一覧から） ②query 文字列の pass-through（ls -q、debounce 100-150ms） ③エラー（exit 2 + 位置）のインライン表示。TS 側に query parser は持たない（サジェスト用の軽い token 分割まで）。UI 層適用案は破棄。",
		},
		{
			ID:       "t-2qyb",
			Title:    "vista: fleet-sync が配る .github/** が prettier --check を落とす（全 PR 巻き添え）",
			Status:   "done",
			Priority: 2380,
			Labels:   []string{"ci"},
			Repos:    []string{"akira-toriyama/vista"},
			Created:  ts("2026-07-17T11:35:43Z"),
			Updated:  ts("2026-07-17T13:57:21Z"),
			Closed:   ts("2026-07-17T13:57:21Z"),
			Body:     "# vista: fleet-sync が配る .github/** が prettier --check を落とす（全 PR 巻き添え）\n\n**症状**: vista の全 PR が `check:format` で赤。`prettier --check .` が `.github/workflows/taplo.yml` を蹴る（`paths: ['**/*.toml']` の single quote → prettier は double を要求）。t-614w の PR [vista#17](https://github.com/akira-toriyama/vista/pull/17) で発覚。**PR の変更とは無関係**（当該ファイルを 1 バイトも触っていない。branch 上の版は prettier 緑で、main 由来の版だけが落ちる）。\n\n**原因**: fleet-sync bot の `995a9d6 :robot: chore(fleet): sync .github/workflows/taplo.yml` が main を直接更新した。**vista の `ci.yml` は `on: pull_request` のみで main push では走らない** → `pnpm check` に一度も掛からず main に着地し、以降の PR が merge commit 経由で全部巻き添え。\n\n**構造**: vista は fleet の配布物（`.github/workflows/*` `.github/dependabot.yml` `.github/zizmor.yml`）を**自分で書いていないのに `prettier --check .` で lint している**。ローカルで直しても次の fleet-sync が上書きするので**恒久ループ**。\n\n**解の候補**:\n1. **`.prettierignore` に fleet 配布物を追加**（vista 側で完結・既存の「machine-written files — their generators own the formatting」節の思想とそのまま一致。pnpm-lock.yaml / generated/ と同じ扱い）。**推奨**。\n2. fleet 正本（`akira-toriyama/.github`）側を prettier 準拠にする → 全 repo が直るが、配布先ごとの prettier 設定に正本を追従させる構造になり筋が悪い。\n3. `ci.yml` を `on: push: branches: [main]` でも走らせる → 検知は早まるが原因は消えない（1 と併用の価値あり）。\n\n**判断ポイント**: 「fleet 配布物は vista の所有物ではない」を認めるなら 1。他 repo も同じ穴を持っているはず（同じ `prettier --check .` + fleet 配布なら再現）。\n- 🚧 `vista#18` opened\n- ✅ `vista#18` merged → `done`",
		},
		{
			ID:       "t-2tbn",
			Title:    "vista: scaffold — create-tauri-app（Vite+React+TS strict）+ 4層構造 + テスト基盤",
			Status:   "done",
			Priority: 1610,
			Value:    3,
			Effort:   2,
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Created:  ts("2026-07-16T08:35:53Z"),
			Updated:  ts("2026-07-16T09:26:59Z"),
			Closed:   ts("2026-07-16T09:26:59Z"),
			Body:     "# vista: scaffold — create-tauri-app（Vite+React+TS strict）+ 4層構造 + テスト基盤\n\nepic: [[t-fw2m]]／設計 doc: `docs/superpowers/specs/2026-07-16-vista-gui-v1-design.md`\n\n- [x] create-tauri-app（React + TS template）、TS strict 化（+ noUncheckedIndexedAccess / noImplicitOverride / erasableSyntaxOnly）。\n- [x] `src/domain|application|infrastructure|ui` の4層 + `eslint-plugin-boundaries` で依存方向を機械的に禁止（v7 dependencies rule。4種の違反を negative test で発火確認済み）。\n- [x] vitest 2 projects: jsdom（unit、`@tauri-apps/api/mocks` の mockIPC）/ node（実 furrow を叩く contract test 用の枠。furrow 不在時 skip）。\n- [x] shadcn/ui + Tailwind 導入（Tailwind v4 + radix-nova preset。生成物は `src/ui/components/ui` に収め ui 層内に閉じた）。\n\n実装は vista#2（feat/scaffold-t-2tbn）。lint / typecheck / test(14) / vite build / cargo check / dev-server smoke まで green。\n\nメモ（次セッション向け）:\n- eslint-import-resolver-typescript（unrs-resolver）は tsconfig に `references` があると paths 解決に失敗する → root tsconfig から references を外し、`tsconfig.node.json` は `pnpm typecheck` で単体検査する構成にした。\n- boundaries v7 は既定で外部 module への依存を検査しない → `checkAllOrigins: true` が必須（これがないと @tauri-apps 禁止 policy が空振りする）。\n- 次: vista#2 の merge 後、Rust core（furrow 解決・exec・fs-watch）タスクへ。\n- 🚧 `vista#2` opened\n- ✅ `vista#2` merged → `done`",
		},
		{
			ID:       "t-9sa6",
			Title:    "vista: Table(List) view — GH Projects Table 寄せ + 仮想化",
			Status:   "backlog",
			Priority: 660,
			Value:    4,
			Effort:   4,
			Labels:   []string{"ui"},
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Checklist: []ChecklistItem{
				{Text: "列定義 + 表示/非表示 + 並べ替え", Done: false},
				{Text: "40px 行 + hover/選択の Primer 色", Done: false},
				{Text: "sort 2 段", Done: false},
				{Text: "group by + sticky group header", Done: false},
				{Text: "react-virtual 組み込み", Done: false},
				{Text: "セル編集（lane/value/effort）", Done: false},
			},
			Created: ts("2026-07-16T15:27:16Z"),
			Updated: ts("2026-07-16T15:27:16Z"),
			Body:    "設計 doc の List view を GH Projects Table の視覚言語で実装（memex 実 CSS 由来の実値は t-n2fc body 参照）。\n- 行高 **40px 固定**・セル padding 12px・行 hover = bgColor-muted・選択 = accent-muted + box-shadow 縁\n- 列ヘッダ 12px semibold・列の表示/非表示・ドラッグ並べ替え・sort（primary+secondary の 2 段、GH 同）\n- group by（lane 等）時は sticky group header 行（色 chip + muted 集計）\n- インライン編集は GH のセル編集モデル（Enter でセル編集トグル）を参考に、v1 は single select 系（lane/value/effort）から\n- **@tanstack/react-virtual v3 を初版から**（数百〜数千行想定。後付けは行高/scroll/sticky 制約で高くつく）\n\n出典: GH docs Table layout / memex module.css（t-n2fc 参照）/ https://tanstack.com/virtual/latest",
		},
		{
			ID:       "t-7wdg",
			Title:    "vista: Board 拡張 — 列 count/field sum + column WIP limit",
			Status:   "backlog",
			Priority: 680,
			Value:    3,
			Effort:   2,
			Labels:   []string{"ui"},
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Checklist: []ChecklistItem{
				{Text: "列 count 常時表示", Done: false},
				{Text: "value/effort sum の display option", Done: false},
				{Text: "WIP limit 設定 UI + 超過ハイライト", Done: false},
			},
			Created: ts("2026-07-16T15:27:16Z"),
			Updated: ts("2026-07-16T15:27:16Z"),
			Body:    "GH Projects の Board 付加機能 2 点（ユーザー 2026-07-17: ほぼ全て再現したい・v1 必須ではない）:\n- **列ヘッダに count**（CounterLabel: 12px semibold・radius 20px・bg neutral-muted）+ display options で value/effort 合計の表示 toggle（GH の Field sum 相当）\n- **column WIP limit**: 列ごとに上限値を設定 → ヘッダに「n / limit」表示・超過で列ハイライト。**強制はしない**（GH 同。DnD も add もブロックしない）。furrow に概念が無いので GUI 側設定（plugin-store）。ユーザーの Ready lane「WIP 2-3」運用に効く。\n\n出典: GH docs Board layout（Set column limit）",
		},
		{
			ID:       "t-ehk7",
			Title:    "furrow: typed query -q — GH Projects 互換の filter 構文",
			Status:   "backlog",
			Priority: 570,
			Value:    5,
			Effort:   4,
			Labels:   []string{"cli"},
			Repos:    []string{"akira-toriyama/furrow", "akira-toriyama/vista"},
			Checklist: []ChecklistItem{
				{Text: "internal/query: lexer + parser + AST（エラー位置つき）", Done: false},
				{Text: "評価器: shard フィールドへの適用（lane/label/repo/type/parent/value/effort/priority/自由語）", Done: false},
				{Text: "ls -q 結線（-r/-l/-s と AND 合成）", Done: false},
				{Text: "next/revisit にも -q", Done: false},
				{Text: "table tests + fuzz + golden", Done: false},
				{Text: "help/README/schema ドキュメント", Done: false},
				{Text: "PR 作成 → CI 緑 → merge（ユーザー承認済み 2026-07-17）", Done: false},
			},
			Created: ts("2026-07-16T15:47:39Z"),
			Updated: ts("2026-07-16T15:47:39Z"),
			Body:    "**vista filter bar (t-jv3j) の正本ロジック**。ユーザー決定 2026-07-17: 「迷ったら、仮に TUI を作るならロジックが冗長になるか」で判断 → 冗長になる → furrow 側に置く（この判断規範は今後の同種の迷いにも適用）。**PR は Claude が出し、merge まで OK**。速度でなく品質重視。\n\n## 仕様（GH Projects filter 構文の互換サブセット）\n\n`ls`（まず）/ `next` / `revisit` に `-q <query>` を追加。既存 `-r/-l/-s` との合成は AND（-q 内の同種 field とも AND）。\n\n- `field:value` — lane(status alias)/label/repo/type/parent/id + value/effort/priority\n- カンマ = OR（`label:ui,dx`）、同一 qualifier 繰返し = AND（GH 同）\n- `-` 前置 = 否定（`-lane:done,icebox`）\n- `no:<field>` / `has:<field>`（値が空/ある。label, parent, repo, value, effort…）\n- 数値: `value:>3` `effort:<=2` `priority:1600..1700`（比較 + `..` 範囲）\n- 自由語（qualifier なし）= title/body の単語先頭一致（GH 同・mid-word 不一致）。`\"...\"` で空白含む値\n- 将来拡張枠（初版外で可）: ワイルドカード `label:*ui*`、`is:actionable/blocked/stuck`（furrow 計算フラグ — これは GH に無い furrow ならでは）\n\n## 実装メモ\n\n- parser は internal/query パッケージに分離（lexer + 再帰下降で足りる規模）。エラーは exit 2 + 位置情報 + candidates（did-you-mean 流儀に合わせる）\n- table tests + go fuzz（parse が任意入力で panic しない）+ golden（--json 結果）\n- docs: help text + README の query 節\n- GH 構文全文: https://docs.github.com/en/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/filtering-projects\n\nvista 側: t-jv3j が本タスクに依存（query pass-through + サジェスト UI に再スコープ済み）。",
		},
		{
			ID:       "t-fw2m",
			Title:    "vista: furrow GUI v1 — Tauri v2 + React（kanban／依存グラフ／CRUD）",
			Status:   "in-progress",
			Priority: 470,
			Type:     "epic",
			Value:    4,
			Effort:   5,
			Repos:    []string{"akira-toriyama/vista"},
			Created:  ts("2026-07-16T08:35:53Z"),
			Updated:  ts("2026-07-17T05:13:04Z"),
			Body:     "# vista: furrow GUI v1 — Tauri v2 + React（kanban／依存グラフ／CRUD）\n\n**GUI epic（[[t-0007]] の後継・実装編）**。方式選定は 2026-07-16 に **Tauri v2** で決着\n（Obsidian は task/project 管理機能の不足で棄却 → [[t-0053]]）。\n\n設計の正本: vista repo `docs/superpowers/specs/2026-07-16-vista-gui-v1-design.md`\n（branch docs/gui-v1-design、レビュー後 main へ）。\n\n## 骨子\n\n- 殻 = Tauri v2。**furrow は同梱せずホストの furrow（PATH の source wrapper）を呼ぶ**。\n- ロジック正本は furrow 一本（vista は shard を直接読み書きしない・CLI の --json のみ）。\n  **不足は furrow へ PR**（GUI 側で回避実装しない）。\n- TS 4層（domain / application / infrastructure / ui）。read-write・task CRUD。中央ボード固定。\n- 差別化の本丸 = **依存グラフを一級ビューに**（主要 PM ツールに真の graph view は不在、調査済み）。\n\n## 実装順（子 task）\n\nscaffold → Rust core → adapter+Query → Board DnD（furrow ギャップ2件が先行）→ filter bar\n→ detail → Graph view → palette/keyboard → add UI+sync 統合。\n- 🚧 `vista#1` opened\n\n**2026-07-16: 設計承認・設計セッション完了。** 設計 doc は vista PR #1（https://github.com/akira-toriyama/vista/pull/1）でレビュー待ち → merge 後は `docs/superpowers/specs/2026-07-16-vista-gui-v1-design.md` が正本。会話での追加決定: CLI=Go／UI=TS の A 構成を維持し、型共有は `furrow schema` → TS codegen で吸収（[[t-g8bn]] に反映済み）。**次セッション希望: PR #1 を merge のうえ、[[t-2tbn]]（scaffold）から着手**（furrow 側の gate 2 件 [[t-phgp]]/[[t-ecfm]] を先にやるのも可・並行可能）。\n- 🔗 `vista#1` merged\n\n2026-07-16 ユーザー決定: **UI の北極星 = GitHub Projects**（https://github.com/users/akira-toriyama/projects/5 ）。視覚言語・密度・保存ビュー=タブの操作感をこれに寄せる（実装 task: [[t-n2fc]]）。\n\n… (truncated in the POC fixture)",
		},
		{
			ID:       "t-9m2q",
			Title:    "vista: Dialog テストの必須 assertion をルール化（accessible name + close 経路）",
			Status:   "backlog",
			Priority: 605,
			Value:    3,
			Effort:   3,
			Labels:   []string{"ui"},
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Deps:     []string{"t-614w"},
			Created:  ts("2026-07-17T06:58:54Z"),
			Updated:  ts("2026-07-17T15:04:56Z"),
			Body:     "# vista: Dialog テストの必須 assertion をルール化（accessible name + close 経路）\nt-wf4p の副産物。**3 ライブラリすべてに共通する silent な穴**を実測で見つけたので、家風「lint/test で防げることは Claude が人力でやらない」に従いルール化する。\n\n## 塞ぐ穴（すべて実測。Base UI / React Aria / Radix の 3 者とも silent）\n\n1. **`open` を渡して `onOpenChange` を省略** → 閉じられない modal。3 者とも `open?`/`onOpenChange?` が**独立 optional**（判別可能ユニオンでない）ので **tsc は原理的に見えない**。throw も warn も無い。**render assertion は全部緑。**\n2. **Dialog に accessible name が無い** → 3 者中 2 者が silent。しかも **`jsx-a11y-x` は compound component に完全に盲目**（intrinsic DOM 要素しかモデル化しない。無名 dialog に eslint エラー 0 を実測）。出荷中の Radix 1.1.19 は**さらに悪く**、`aria-labelledby` を無条件に出すので **dangling ARIA reference** になる（属性が無いより厳密に悪い。上流修正 e4e06649 は 2026-07-10 で未リリース）。\n\n## 案\n\n- **Dialog テストの必須 2 assertion**: `toHaveAccessibleName()` と **close 経路**（Close クリック + Escape の両方）。共有 test helper（`renderDialog` 的なもの）か custom eslint rule のどちらが適切か検討。\n- helper 案なら「presenter/hook 分離」の様式に乗る形にする（t-rz61）。\n\n## 参考: 検証の罠（t-wf4p で実際に踏んだ。規約に書く価値がある）\n\n- **menu の focus は rAF で動くので `waitFor` で落ち着かせてから assert する。**\n  ⚠️ **訂正（実測）**: 調査中に一度「pointer open は APG 準拠で意図的に trigger へ focus を残す設計だから `{ArrowDown}` の後に assert しろ」という規約案が出たが、**これは偽**。3 回連続で実測すると `immediately` は `button[trigger]` / `button[trigger]` / `div[menu]` と**非決定的**で、`settled` は**毎回 `div[menu]`**（`src/ui/_bakeoff/menufocus.probe.test.tsx`）。Base UI は**ポインタ open でも focus を popup に入れる**。rAF 前の状態をたまたま観測して「設計」と合理化していただけ。**レースから導いた規約を家風に焼き付けるところだった。**\n- **Base UI の `ScrollLocker.release()` は `setTimeout(fn, 0)` で遅延解除**。unmount 直後の同期 assert は**存在しないリークを報告する** → `waitFor`。\n- **`body.style.overflow` を assert しない**。jsdom/cssstyle は shorthand と longhand を別枠で持つので、Base UI（shorthand で書き longhand で復元）が**偽のリークに見える**。longhand か `data-base-ui-scroll-locked` 属性を見る。\n- **jsdom は 1 ファイル 1 document**。`cleanup()` は React tree を unmount するだけで body の inline style を戻さない → **前の候補の残留が次の候補の挙動として読まれる**。`beforeEach` でリセット。\n- **`{/* @ts-expect-error */}` は JSX 内で黙って無視される**。使ったら TS2578 で効いていることを自己検証する。",
		},
		{
			ID:       "t-phgp",
			Title:    "furrow: reorder --before/--after <id>（相対位置指定・atomic）を追加",
			Status:   "done",
			Priority: 1620,
			Value:    4,
			Effort:   2,
			Repos:    []string{"akira-toriyama/furrow"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T11:26:43Z"),
			Closed:   ts("2026-07-16T11:14:01Z"),
			Body:     "# furrow: reorder --before/--after <id>（相対位置指定・atomic）を追加\n\n**vista GUI（[[t-fw2m]]）の Board DnD が依存**。現状 `reorder <id> <priority>` は絶対値のみで、GUI の「間に挿す」DnD はクライアントが midpoint を計算し、sparse priority の隙間枯渇時は複数 task の再採番＝複数 write に割れる。\n\n- `furrow reorder <id> --before <ref-id>` / `--after <ref-id>` を追加（絶対値指定と排他）。\n- 隙間枯渇時の再採番も**同一 write 内で atomic に**（all-or-nothing は dep コマンドと同じ契約）。\n- --json は影響を受けた task 群を返す。\n\n2026-07-16 会社PC Claude セッションが着手 (in-progress)。t-ecfm と合わせて相対位置ロジックを core に置き、reorder→set の順で 2 PR に分ける方針。\n- 🚧 `furrow#142` opened\n- ✅ `furrow#142` merged → `done`\n\n2026-07-16 完了: furrow#142（squash ce51b10）。reorder --before/--after <ref> を追加 — 同一レーン相対挿入。隙間があれば midpoint 1 write、枯渇時は同一 write 内でレーン全体を respace（all-or-nothing）し --json に renumbered [{id,from,to}] を付与。respace された隣人の updated は意図的に進めない（staleness 保護）。lane 跨ぎ ref は exit 2・不在 ref は exit 1。merge 時の CI apply が lane を done に自動更新。",
		},
		{
			ID:       "t-pk4f",
			Title:    "vista: Slice panel（左パネル絞り込み）",
			Status:   "backlog",
			Priority: 690,
			Value:    2,
			Effort:   3,
			Labels:   []string{"ui"},
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Deps:     []string{"t-jv3j"},
			Created:  ts("2026-07-16T15:27:16Z"),
			Updated:  ts("2026-07-16T15:27:16Z"),
			Body:     "GH Projects の Slice by: 左パネルに field 値一覧（label / repo / lane / parent）を出し、値クリックで view をその値に絞る。**filter bar と独立に効き、併用される**（GH 仕様）。全 layout で共通。\n\nfilter bar と役割が重なるため優先度低（ユーザー: ほぼ全て再現したいが v1 必須ではない）。GH では slice 可否 field が group by と異なる（labels は slice 可・group 不可）点に注意。\n\n出典: GH docs 各 layout ページの Slicing by field values 節",
		},
		{
			ID:       "t-g8bn",
			Title:    "vista: FurrowPort／adapter + TanStack Query 統合 + contract test",
			Status:   "done",
			Priority: 1610,
			Value:    4,
			Effort:   3,
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Deps:     []string{"t-6etg"},
			Checklist: []ChecklistItem{
				{Text: "domain の Task 型は手書きせず furrow schema の JSON Schema から TS 型を codegen（furrow と機械的に同期）", Done: true},
			},
			Created: ts("2026-07-16T08:35:53Z"),
			Updated: ts("2026-07-16T12:59:05Z"),
			Closed:  ts("2026-07-16T12:59:05Z"),
			Body:    "# vista: FurrowPort／adapter + TanStack Query 統合 + contract test\n\n- domain: `Task`/`Lane`/`DepGraph` 不変モデル + 純ロジック（DAG 構築等）。Tauri/React 非依存。\n- application: `FurrowPort` interface + usecase hooks。\n- infrastructure: `TauriFurrowAdapter`（`@tauri-apps/*` を import する唯一の層）。\n- TanStack Query v5: queryKey 階層（`['tasks']`／`['tasks','list',filters]`／`['tasks','detail',id]`）、`staleTime: Infinity` + `networkMode:'always'`、`tasks://changed` → `invalidateQueries` の glue。\n- contract test（node env）: temp dir に `furrow init` した board へ実 furrow で読み書きし adapter の JSON 契約を検証。\n- 🚧 `vista#5` opened\n\n2026-07-16 セッション進捗（PR: https://github.com/akira-toriyama/vista/pull/5）\n\n- [x] codegen: pnpm codegen（furrow schema task → src/domain/generated/ に TS 型 + schema snapshot）\n- [x] domain: Task/TaskDetail/Lane/BoardInfo/MutationReport + 純 buildDepGraph\n- [x] application: FurrowPort IF・FurrowError（exit 0/1/2/3+ と stderr 封筒の typed 化）・queryKeys・QueryClient 既定・hooks（tasks://changed → invalidate glue 含む）\n- [x] infrastructure: createFurrowClient（exec 非依存コア）+ createTauriFurrowAdapter（greet scaffold 置換）\n- [x] contract test: 実 furrow × temp board（16本）+ schema drift guard\n- 発見: add 以外の mutation は {after,before,changed} を返す → MutationReport として型化（undo/toast に有用）\n- 意図的に見送り: port の sync()（sync 統合タスクで）・reorder（furrow t-phgp の --before/--after 待ち）・parent/repo/label 単独編集の port method（detail 編集タスクで）\n\n次セッション希望: PR #5 merge 確認後、Board view (t-t38k) に着手（furrow ギャップ t-phgp/t-ecfm が先行）。\n- ✅ `vista#5` merged → `done`",
		},
		{
			ID:       "t-ecfm",
			Title:    "furrow: lane 移動 + priority を 1 write に（set --priority／--before／--after）",
			Status:   "done",
			Priority: 1630,
			Value:    3,
			Effort:   1,
			Repos:    []string{"akira-toriyama/furrow"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T11:26:43Z"),
			Closed:   ts("2026-07-16T11:25:37Z"),
			Body:     "# furrow: lane 移動 + priority を 1 write に（set --priority／--before／--after）\n\n**vista GUI（[[t-fw2m]]）の Board DnD（cross-column）が依存**。lane を跨いで特定位置へ drop する操作が現状 `move` + `reorder` の 2 write（= 2 commit・2 fs event）に割れる。\n\n- `set` に `--priority <n>`（および reorder の相対指定が入るなら `--before/--after`）を追加し、`-s <lane> --priority …` を単一 write に。\n\n2026-07-16 会社PC Claude セッションが着手 (in-progress)。t-phgp の相対位置ロジック実装後、set に --priority/--before/--after を載せる。\n- 🚧 `furrow#143` opened\n- ✅ `furrow#143` merged → `done`\n\n2026-07-16 完了: furrow#143（squash f1cf70e）。set に --priority(-p)/--before/--after を追加 — set <id> -s <lane> --before <ref> で列跨ぎ drop（lane+位置）が 1 write に。相対位置は移動先レーン基準、respace/renumbered 契約は reorder(#142) と同一、位置系 3 フラグは排他。App.Set は renumbered を返す signature に変更（破壊的変更は Go API のみ・CLI 互換）。",
		},
		{
			ID:       "t-rmtc",
			Title:    "vista: view tabs + 保存ビュー（GH モデル）+ plugin-store 永続化",
			Status:   "backlog",
			Priority: 670,
			Value:    5,
			Effort:   4,
			Labels:   []string{"ui"},
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Deps:     []string{"t-jv3j"},
			Checklist: []ChecklistItem{
				{Text: "plugin-store adapter（infrastructure 層・FurrowPort と同様に port 化）", Done: false},
				{Text: "view model（layout/filter/sort/group/fields/order）+ dirty 判定", Done: false},
				{Text: "タブバー UI（dot・Save/Discard・New view・D&D 並べ替え）", Done: false},
				{Text: "<Activity> でタブ state 保持", Done: false},
			},
			Created: ts("2026-07-16T15:27:16Z"),
			Updated: ts("2026-07-16T15:27:16Z"),
			Body:    "設計 doc「1 データセット + 保存ビュー = タブ」の実装。GH Projects の編集モデルに寄せる（t-n2fc 北極星）:\n- view = layout(Board/Table/Graph) + filter + sort + group + 表示 field + 手動並び順 の組\n- **変更はまず自分だけ → タブ名横に dirty dot → 明示 Save で永続化**（GH と同じ。Save changes / Discard）\n- タブ視覚（memex 実値）: タブバー bg inset + inset 下線 shadow、選択タブ = bg default + border（下辺なし）+ radius 6px 6px 0 0、非選択 fgColor-muted、+ New view、タブ D&D 並べ替え\n- **<Activity>（React 19.2）で非表示タブの state 保持**（スクロール位置・選択が残る）\n- 永続化は **@tauri-apps/plugin-store**（infrastructure 層 adapter。localStorage は Rust 不可視・webview データ消去で消えるため不採）\n\n出典: GH docs Managing views / memex module.css / https://v2.tauri.app/plugin/store/",
		},
		{
			ID:       "t-614w",
			Title:    "vista: Radix → Base UI 移行（primitives 入れ替え）",
			Status:   "done",
			Priority: 515,
			Value:    4,
			Effort:   2,
			Labels:   []string{"ui"},
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Deps:     []string{"t-2qyb", "t-wf4p"},
			Created:  ts("2026-07-17T06:58:54Z"),
			Updated:  ts("2026-07-17T14:06:15Z"),
			Closed:   ts("2026-07-17T14:06:15Z"),
			Body:     "# vista: Radix → Base UI 移行（primitives 入れ替え）\nt-wf4p の選定結果（**Base UI `@base-ui/react` 1.6.0**）を main に反映する。台帳・根拠・実測は **t-wf4p の body が正本**。証拠ブランチ = [`t-wf4p/headless-ui-bakeoff`](https://github.com/akira-toriyama/vista/tree/t-wf4p/headless-ui-bakeoff)（**commit 45da9d0 · push 済 · マージしない**）。\n\n## ⚠️ 着手時の最初の 1 手\n\nvista の checkout は **`t-wf4p/headless-ui-bakeoff` の上に居る**（bake-off の 3 実装・中立スイート・AX 検証ページ・`_ergonomics` scratch が乗っている）。\n**この PR は main から切り直す**:\n\n```sh\ngit -C …/vista checkout main && git -C …/vista switch -c <branch>\n```\n\nbake-off ブランチのものは 1 行も持ち込まない（`src/ui/_bakeoff/` `src/ui/_ergonomics/` と、それ用の `eslint.config.js`/`vitest.config.ts`/`knip.json` の除外・`src/main.tsx` の `VITE_BAKEOFF` 分岐は**全部使い捨て**）。ただし **`knip.json` の `\"ignore\": [\"src/ui/primitives/**\"]` だけは本番でも必要**（下記）。\n\n**今より安くなることは二度と無い**: src 内の radix 使用は `src/ui/primitives/button.tsx:3` の `Slot` **1 行のみ**、`asChild` 呼び出し側 **0 件**。primitive があと 3 つ着地した瞬間にこの窓は閉じる。\n\n## 手順（1 PR）\n\n- [x] `components.json`: `\"style\": \"radix-nova\"` → `\"base-nova\"`（1 語。`aliases` はそのまま。dry-run でバイト同一の 4 ファイル計画を確認済）\n- [x] `pnpm add @base-ui/react` + `pnpm remove radix-ui`（依存 77 → 12。`aria-hidden` と `react-remove-scroll` が依存ごと消える）→ **予告どおり**。lock −1560 行、`radix|aria-hidden|react-remove-scroll` の grep hit 0\n- [x] `pnpm dlx shadcn@latest add dialog popover dropdown-menu` — **部品名は `dropdown-menu`。`menu` は 404** → 予告どおり\n- [x] ~~⚠️ **生成物の手直し**: `icon-placeholder` の漏れ import → lucide に置換~~ **← 誤り。不要だった（実測で反証）**。漏れているのは **registry の raw JSON だけ**で、CLI は `iconLibrary: \"lucide\"` により**全経路で書き換える**（`--dry-run --view` も書き換え後を出す）。同一 shadcn **4.13.0** で確認。生成物の import は最初から `lucide-react`。**原因 = registry のソースを読んで CLI 出力と誤読した**（t-wf4p §5.5「計器を実物と読み違える」の再発）。glossary には罠ではなく**反証**として記載（将来「直そう」としないように）\n- [x] ~~`button.tsx`: `Slot` → `render` prop（キャスト 1 行が要る）~~ **← 不要だった**。base-nova の素の button は `@base-ui/react/button` の `ButtonPrimitive` を直接使う設計で、自前の `render` 配線もキャストも要らない。`check:types` 緑（**故意の型エラーを注入して tsc が当該ファイルを実検査していることも確認済**）。ついでに upstream が `data-variant`/`data-size` を落としているが、**使用箇所 0 件**を grep 確認して素の出力をそのまま採用（vendored = 無改変が原則）\n- [x] **`knip.json` に `\"ignore\": [\"src/ui/primitives/**\"]`** — **必須は正しい。ただし理由が違った**: 予告「未使用 export 4 件」ではなく **`Unused files` 3 件**（dialog/popover/dropdown-menu をまだ誰も import していないため）。ignore 無しで `check:deadcode` exit 1 を実測 → 追加で緑\n- [x] `glossary.md`: `primitives` を base-nova に更新 + `base-nova` / `render prop` / `modal 三状態` / 罠 2 件（**trap-focus の aria-hidden** ・ **className-as-function**）を新設。すべて installed 1.6.0 の dist で実証してから記載\n- [x] `eslint.config.js` / `vitest.config.ts` は **変更不要** → 予告どおり（`pnpm check` 緑で確認）\n\n… (truncated in the POC fixture)",
		},
		{
			ID:       "t-px9p",
			Title:    "vista: command palette + keyboard（Cmd+K・mnemonics・multi-select bulk）",
			Status:   "backlog",
			Priority: 630,
			Value:    3,
			Effort:   3,
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Deps:     []string{"t-r7wr"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T15:28:28Z"),
			Body:     "# vista: command palette + keyboard（Cmd+K・mnemonics・multi-select bulk）\n\n- `Cmd+K` palette = navigation + 全 mutation（fuzzy）。\n- 単キー mnemonics（`L` lane／`V` value／`E` effort／`#` labels／`M B` blocked-by picker）、`G` chords（`G B`/`G G`/`G L`）、`?` = shortcut sheet。\n- **multi-select → palette が選択全体に作用**（Height の bulk パターン）。atomic 化は furrow の複数 id mutation（[[t-2kxt]]）待ちだが gate しない（逐次呼びで先行）。\n\n2026-07-17 ユーザー決定: **基本語彙 = GH Projects 作法 + 衝突しない範囲で Linear 風単キー mnemonics 併用**。\nGH 側（公式 shortcuts より）: **Enter / Shift+Space = カード move モード開始 → ↑↓ 列内・←→ 隣列・Cmd+矢印で端、Enter 確定 / Esc キャンセル**（マウス不要 DnD。sort 適用中は列内移動不可の排他も GH 同）／ **Space = 選択 item を side-peek で開く**（t-r7wr 連動）／ **e = archive**（vista では done→archive 写像に留意）／ **Cmd+F = filter bar フォーカス**／ Shift+↑↓ = 選択拡張・Cmd+A = 全選択 ／ Cmd+K = palette（既定案のまま）。\nLinear 風単キー（L lane / V value / E effort / # labels / M B blocked-by / G chords）は上と衝突しないので維持。`?` = shortcut sheet に両系統を載せる。\n出典: https://docs.github.com/en/get-started/accessibility/keyboard-shortcuts（Projects 節）",
		},
		{
			ID:       "t-0esb",
			Title:    "vista: Graph view — 依存 DAG（@xyflow/react + elkjs）を一級ビューに",
			Status:   "backlog",
			Priority: 620,
			Value:    5,
			Effort:   4,
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Deps:     []string{"t-fn4k", "t-t38k"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T15:26:21Z"),
			Body:     "# vista: Graph view — 依存 DAG（@xyflow/react + elkjs）を一級ビューに\n\n**差別化の本丸**（調査 2026-07: Linear/GitHub Projects/Plane/Vikunja いずれも依存は sidebar リスト + Gantt 矢印が天井、真の graph view 不在。唯一の類例は Taskheat）。\n\n- 全ボード（filter 適用後）の DAG。`elk.layered` を web worker で、左→右・lane で層。\n- node = React component、status 色分け・blocked 強調・click → peek。\n- **node 間 drag で dep 作成**（`furrow dep`）、edge 削除 = `dep --rm`。\n- task detail 内に ±1〜2 hop の neighborhood mini-graph。\n- 簡素で足りるなら `@dagrejs/dagre` 3.x（同期）へのフォールバック可。",
		},
		{
			ID:       "t-6etg",
			Title:    "vista: Rust core — ホスト furrow 解決・exec・.furrow fs-watch イベント",
			Status:   "done",
			Priority: 1600,
			Value:    4,
			Effort:   3,
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Deps:     []string{"t-2tbn"},
			Created:  ts("2026-07-16T08:35:53Z"),
			Updated:  ts("2026-07-16T10:27:36Z"),
			Closed:   ts("2026-07-16T10:27:36Z"),
			Body:     "# vista: Rust core — ホスト furrow 解決・exec・.furrow fs-watch イベント\n\nRust は極薄・ビジネスロジックなし（設計 doc 参照）。\n\n- **furrow 同梱なし**: 起動時に login shell（`zsh -lc 'command -v furrow'`）で絶対パス解決→キャッシュ、設定で上書き可。解決失敗は UI でパス入力を促す。\n- exec: shell plugin `Command.create` で `furrow <cmd> --json`。exit code（0/1/2/3+）+ stderr の `{\"error\":{code,...}}` を typed error として webview へ。capabilities は最小権限。\n- fs-watch: `notify` + debouncer-full で `.furrow/` を watch（editor の multi-event burst を coalesce）→ `tasks://changed` emit。macOS FSEvents の `/private` prefix は canonicalize。\n- 起動時 `furrow board --json` pre-flight（`writable:false` → read-only mode 通知）。\n- 🚧 `vista#4` opened\n- ✅ `vista#4` merged → `done`\n\n2026-07-16 完了（vista#4 merge・main=55d6f71）。plan = vista `docs/superpowers/plans/2026-07-16-rust-core.md`（TDD・module 毎 commit）。unit test 23 件は全て環境非依存（furrow 不要・CI で `cargo test --locked` 実行）。\n\n## 実装結果（上記記述からの逸脱 3 点・理由は plan doc）\n\n- **shell plugin 不採用 → custom command 5 本**: `furrow_resolve` / `furrow_set_path(path)` / `board_info` / `furrow_exec(args)` / `watch_start`。shell plugin の scope は静的 JSON で実行時解決パスを表現できず、custom command の方が最小権限（webview に exec capability を一切渡さない）。\n- **typed error の写像は TS 層へ**: Rust は raw `{code, stdout, stderr}` を返すのみ（`CoreError {code, message}` は Rust 側の失敗: furrow-not-found / furrow-path-invalid / board-config-not-found / board-config-invalid / spawn-failed / watch-failed）。pre-flight（`writable:false` 解釈）も adapter task の責務。\n- **board dir は furrow config parse**: GUI の cwd（`/`）は scope 外で furrow が board を見つけられないため、`~/.config/furrow/config.toml` 先頭 `[[board]]` を parse し furrow を board root cwd で実行。furrow gap 案 → [[t-27m7]]（`furrow boards --json`）。\n\n次セッション希望: adapter + Query 統合（TS 4層の infrastructure/application、contract test 含む）へ。frontend の greet デモ残骸の除去もそこで。",
		},
		{
			ID:       "t-n2fc",
			Title:    "vista: UI を GitHub Projects の look & feel に寄せる",
			Status:   "ready",
			Priority: 560,
			Type:     "task",
			Value:    4,
			Effort:   3,
			Labels:   []string{"ui"},
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Created:  ts("2026-07-16T14:17:29Z"),
			Updated:  ts("2026-07-17T15:04:56Z"),
			Body:     "ユーザー指示（2026-07-16）: **UI の最終目標（北極星）= GitHub Projects**。参照: https://github.com/users/akira-toriyama/projects/5\n\n- Board / Table(List) / タブ型の保存ビューなど、視覚言語・密度・操作感を GitHub Projects に寄せる。\n- 設計 doc の「1 データセット + 保存ビュー = タブ（GitHub Projects モデル）」を UI 面でも徹底する。\n- 対象: 配色・カード密度・列ヘッダ・フィルタバー・+ Add ボタン等の見た目、キーボード操作の作法。\n- vista 差別化要素（Graph view / blocked 旗 / wikilink peek）は保ちつつ、基本語彙を GitHub Projects に合わせる。\n\n## 調査結果（2026-07-17・Primer/memex 実値）と再スコープ\n\nこのタスク = **視覚言語基盤（design tokens）+ Board view の GH 化**に絞る。Table/tabs/WIP limit 等は分割済み（t-9sa6/t-rmtc/t-7wdg/t-pk4f/t-7mcc）。\n\n**ソース**: @primer/primitives v11.9.0 の dist/css 実値 + memex（Projects V2 本体）の production CSS（https://github.githubassets.com/assets/memex.604e4a36b4ee437c.module.css ）から抽出。詳細は調査レポート全文をこのタスクの実装セッションで参照（下の要約で大半は足りる）。\n\n**コア tokens（light / dark）**: bg default #ffffff/#0d1117・muted #f6f8fa/#151b23・inset #f6f8fa/#010409 ／ fg default #1f2328/#f0f6fc・muted #59636e/#9198a1 ／ border default #d1d9e0/#3d444d ／ accent fg #0969da/#4493f8・accent muted bg #ddf4ff/#388bfd1a ／ 行 hover=bgColor-muted・選択=selection #0969da33/#1f6febb3。danger #d1242f/#f85149、success #1a7f37/#3fb950、attention #9a6700/#d29922、done #8250df/#ab7df8。\n\n**密度/形状**: 基本 14px（small 12px）・radius 6px 既定・control 高 32px・spacing 4/8/12/16・focus ring 2px accent。**dark は影でなく枠**（全 shadow に 0 0 0 1px #3d444d）。\n\n**Board 実値**: 列 width 350px 固定・radius 6px・border 1px・**bg = inset**（dark では canvas より暗い #010409）。列 header: 色付き丸 16px(border 2px の輪郭円) + 名前 semibold + count（CounterLabel 12px semibold・radius 20px・bg neutral-muted）。card: radius 6px・border 1px・bg default・**shadow なし**（drag 中のみ resting-medium + opacity .5）・padding 8px 0 12px（内容左右 12px）・タイトル 14px。card 構成: ①12px muted のメタ行 ②タイトル ③labels/assignee 行（margin-top 8px, gap 4px）。DnD sash = 4px 厚 accent-emphasis。選択 = bg accent-muted + border accent + box-shadow 1px。\n\n**lane 色対応**（single select 8 色 display scale より。light: bg/fg、dark: bg/fg）: inbox=GRAY #e8ecf2/#5c6570・#1c1c1c/#92a1b5 ／ backlog=BLUE #d1f0ff/#005fcc・#001a47/#4da0ff ／ ready=GREEN #caf7ca/#2b6e3f・#122117/#41b445 ／ in-progress=YELLOW #ffec9e/#805900・#2e1a00/#d3910d ／ done=PURPLE #f1e5ff/#783ae4・#211047/#b687f7 ／ icebox=GRAY。= ユーザーの Project #5 の Status 色と同一対応。\n\n**実装方針**: Primer の CSS 変数名（--bgColor-* / --fgColor-* / --borderColor-* / --display-*）をそのまま :root/.dark に定義し、Tailwind v4 @theme から var() 参照で張るのが最短（shadcn の既存変数と併存させ、段階的に置換）。font は Geist 継続で可（Mona Sans に寄せるかは実装時判断・優先度低）。\n\n**進め方**: ①tokens 基盤（CSS 変数 + Tailwind 統合 + light/dark） ②Board を実値へ（列 350px/inset bg/header 色丸+count/card 構成） ③filter bar 帯・+ Add item 行の見た目は各 task で。",
		},
		{
			ID:       "t-7mcc",
			Title:    "vista: Board group by（swimlane）",
			Status:   "backlog",
			Priority: 700,
			Value:    3,
			Effort:   4,
			Labels:   []string{"ui"},
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Created:  ts("2026-07-16T15:27:16Z"),
			Updated:  ts("2026-07-16T15:27:16Z"),
			Body:     "GH Projects は Board でも group by = swimlane（横帯）。候補 field: repo / parent(epic) / type。設計 doc では v1 外（Vikunja の card ネストは最多苦情 → swimlane が正解筋）。GH の一貫規則を踏襲: グループへの drop でそのグループの値を適用・グループ内での新規追加は値を自動セット。sort 適用中は列内手動並べ替え不可（GH の排他ルール）も合わせて実装時に考慮。\n\n出典: GH docs Board layout（grouping）",
		},
		{
			ID:       "t-fn4k",
			Title:    "vista: Vitest Browser Mode project 追加（実ブラウザ interaction / visual / axe）",
			Status:   "backlog",
			Priority: 610,
			Value:    4,
			Effort:   3,
			Labels:   []string{"testing"},
			Repos:    []string{"akira-toriyama/vista"},
			Checklist: []ChecklistItem{
				{Text: "browser project 追加（playwright provider）", Done: false},
				{Text: "mockIPC のスモーク確認", Done: false},
				{Text: "Board DnD の interaction test（userEvent.dragAndDrop）", Done: false},
				{Text: "toMatchScreenshot で board の visual regression 1 本", Done: false},
				{Text: "axe-core smoke（board view violations 0）", Done: false},
				{Text: "CI（headless）で安定して回ることを確認", Done: false},
			},
			Created: ts("2026-07-16T15:25:44Z"),
			Updated: ts("2026-07-17T02:04:09Z"),
			Body:    "Vitest 4.0 で Browser Mode が stable（visual regression toMatchScreenshot 同時導入）。3 本目の project として追加（@vitest/browser-playwright + chromium headless + vitest-browser-react、include: **/*.browser.test.tsx）。unit(jsdom) は維持 = 段階導入が公式推奨形。\n\n必要性:\n- **pragmatic-dnd は jsdom で本質的に検証不能**（実座標 getBoundingClientRect ベースの closest-edge hitbox。Atlassian 自身が jsdom 用 polyfill を別配布 = 動かない証左）→ Board DnD の interaction test はここで\n- **@xyflow/react は ResizeObserver/getBBox 依存**で公式が実ブラウザ推奨 → **Graph view (t-0esb) の前提**\n- axe-core 直呼びで view 単位 a11y smoke（vitest-axe は停滞のため不使用）\n- mockIPC が browser mode でも動くかは導入時スモークで確認（window patch なので動く見込み）\n\n出典: https://vitest.dev/blog/vitest-4 / https://reactflow.dev/docs/guides/testing/ / https://atlassian.design/components/pragmatic-drag-and-drop/optional-packages/unit-testing/\n\n2026-07-17: React Compiler が vite/vitest 両 config に配線済み — browser project を足す時も babel plugin (babel-plugin-react-compiler) を同様に通すこと。jsdom 側の残ギャップは DnD interaction のみ(planDrop/optimisticPriority は t-v5xg の PBT で不変条件カバー済み)。ViewBoundary (t-ed0y) が入ったので suspense/error の browser 検証も対象に。",
		},
		{
			ID:       "t-r7wr",
			Title:    "vista: Task detail — side-peek + full page・md render・checklist・relations 編集",
			Status:   "backlog",
			Priority: 600,
			Value:    4,
			Effort:   4,
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Deps:     []string{"t-t38k", "t-wf4p"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T15:47:40Z"),
			Body:     "# vista: Task detail — side-peek + full page・md render・relations 編集\n\n- **side-peek 既定 + Enter で full page**（Plane の tri-mode を2モードに簡約）。j/k 移動に peek 追従。\n- 構成（Linear 踏襲）: title → md body → 右 sidebar（lane/priority/value/effort/labels/repos/parent/relations）。\n- md render: react-markdown v10 + remark-gfm。mermaid は `code` component override（rehype plugin 非使用・同期維持）。`[[id]]` wikilink は hover peek（自作 remark 拡張優勢）。\n- checklist は live render・クリックで `furrow check <id> <index>` toggle。\n- relations: `dep --list --json` の両方向（depends_on/blocks）表示 + 編集。backlinks（`show --backlinks`）も表示。\n- **body(md) の編集は v1 外**（表示のみ。metadata 編集は sidebar から set/retitle/label/repo/parent）。\n\nmemex 実値（2026-07-17 調査）: side panel は右スライドの resizable pane、**幅 clamp(350px, 33vw, 500px)〜（min + clamp(350px,33vw,1000px)）・リサイズハンドル 3px**・bg default・左 border 1px。ヘッダ = id + editable タイトル（20px semibold）+ Close/Pin。**Space キーで選択 task を peek で開く**（t-px9p のキーボード決定と連動）。GH は「repo の issue 表示と同一デザインを panel 内に出す」思想 → vista では detail full page と同一 component を peek に載せる方針が対応物。",
		},
		{
			ID:       "t-f6c3",
			Title:    "vista: add／作成 UI + sync 統合 + schema ガード",
			Status:   "backlog",
			Priority: 640,
			Value:    3,
			Effort:   2,
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Deps:     []string{"t-t38k"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T15:28:28Z"),
			Body:     "# vista: add／作成 UI + sync 統合 + schema ガード\n\n- task 作成（quick-add + フル form: title/lane/priority/value/effort/labels/repos/parent/deps/checklist seed/body 初期値）= `furrow add`。\n- sync 統合: 起動時 `furrow sync`、書き込み後 debounce auto-sync、手動 sync ボタン。`sync-conflict`（exit 3）はバナーで人間へ。\n- schema ガード: 起動時 `furrow board --json` pre-flight → `writable:false` なら閲覧専用バナー + write 封じ。\n- 「削除」= done → `archive` への写像（furrow にハード削除は無い・設計通り）。\n\n2026-07-17 GH 調査反映: 作成 UI は GH の **+ Add item 行**モデルに寄せる（t-n2fc 北極星）。\n- Board 各列の最下部 / Table 最下行に常設の + Add item 行。テキスト入力 → Enter で即作成（= furrow add。draft issue 相当は vista では inbox 直行 or --draft）。\n- **GH の一貫規則を踏襲**: filter が効いた view で追加 → filter のメタデータ（label/repo 等）を新 task に自動適用。列内で追加 → その lane を自動セット。group 内で追加 → group 値を自動セット（swimlane 導入後）。\n- フル form（value/effort/deps/checklist seed 等）は quick-add から展開する二段構え。",
		},
		{
			ID:       "t-wf4p",
			Title:    "vista: headless UI 基盤の吟味 — 候補 clone + 実組みで選定",
			Status:   "done",
			Priority: 515,
			Value:    4,
			Effort:   3,
			Labels:   []string{"ui"},
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Checklist: []ChecklistItem{
				{Text: "候補 4+1 を clone・実装を読む（escape hatch とバグ対応履歴を重点）", Done: true},
				{Text: "dialog/popover/menu を各候補で仮組み・WKWebView で挙動確認", Done: true},
				{Text: "AX tree 比較（peekaboo dump）", Done: true},
				{Text: "選定 + 移行方針 → **Base UI (@base-ui/react 1.6.0)** 採用。移行は別 task", Done: true},
			},
			Created: ts("2026-07-16T15:47:40Z"),
			Updated: ts("2026-07-17T10:38:17Z"),
			Closed:  ts("2026-07-17T10:38:17Z"),
			Body:    "ユーザー 2026-07-17: **Radix はバグで DOM 直操作した経験があり好みでない**。ヘッドレス UI を何個か clone して吟味してよい。**既存 vendored（button 1 個）は全破棄可**。side-peek(t-r7wr)/palette(t-px9p) で Dialog/Popover/Menu の vendor が始まる前 = 今が選定の唯一安い瞬間。\n\n## 候補（clone して吟味）\n\n- **Base UI**（@base-ui/react v1.6 stable — Radix 作者 + MUI + Floating UI。shadcn v4.13 の新規既定）\n- **React Aria Components**（Adobe。a11y の学術的正統・hooks 層に逃げ道あり）\n- **Ark UI**（Zag.js ステートマシン。framework 非依存の内核）\n- **Headless UI v2**（Tailwind Labs。部品少なめだが Tailwind 統合は最良）\n- 基準線として Radix（radix-ui unified v1.6）\n\n## 評価軸\n\n1. **バグ時の逃げ道**（ユーザーの Radix 不満の核心）: escape hatch の設計（render prop / hooks 層 / DOM ref アクセス）、issue 対応速度・open bug の質\n2. a11y 実装品質（AX tree を peekaboo dump で実機確認 — read は host 可）\n3. WKWebView（Tauri）での実挙動（focus trap・portal・positioning）\n4. shadcn レジストリ対応（Base UI/Radix のみ）と、非対応ライブラリを選ぶ場合の自前 vendor コスト\n5. メンテ体制・依存の深さ\n\n## 方法\n\n各候補で dialog + popover + menu を vista に仮組み（使い捨てブランチ）、同一シナリオで比較。結論は本 body に台帳形式（出典・訂正マーカー）で記録し、glossary へ選定結果を 1 行。\n**2026-07-17 実行順を繰上げ（p1632 → 515、t-n2fc の前）。** ユーザー承認済み。理由 = このタスクの body 自身が言う「Dialog/Popover/Menu の vendor が始まる前 = 今が選定の唯一安い瞬間」に **t-n2fc も含まれる**（t-n2fc の対象に「列ヘッダ・+ Add ボタン」があり、GH Projects 化すると列ヘッダの ... メニューと Add の popover が要る）。基盤を決めてから tokens/GH 化に入れば手戻りゼロ。dep で待っているのは t-r7wr（side-peek）→ t-px9p（palette）の 2 本。\n\n現状の前提（t-rz61 merge 済み・vista main）: vendored は **button 1 個のみ**で `src/ui/primitives/button.tsx`（旧 `src/ui/components/ui/` から移動）。`components.json` の aliases は `ui: @/ui/primitives` / `components: @/ui` に更新済み。eslint は `src/ui/primitives/**` だけ react-refresh/only-export-components を off にしている（vendored 前提）。coverage も `src/ui/primitives/**` を exclude 中。**基盤を差し替える時はこの 3 箇所（components.json / eslint.config.js / vitest.config.ts の exclude）と glossary の「primitives」項を一緒に更新すること。**\n\nview の作り方は t-rz61 で確定済み（presenter/hook 注入パターン + coverage 100%）。候補の仮組みもこの様式に乗せて評価すると、実際の書き味が比較できる。規約は vista `CLAUDE.md` / `glossary.md`。\n\n… (truncated in the POC fixture)",
		},
		{
			ID:       "t-t38k",
			Title:    "vista: Board view — kanban DnD（pragmatic-drag-and-drop）+ blocked 旗",
			Status:   "done",
			Priority: 1620,
			Value:    5,
			Effort:   4,
			Repos:    []string{"akira-toriyama/vista"},
			Parent:   "t-fw2m",
			Deps:     []string{"t-ecfm", "t-g8bn", "t-phgp"},
			Created:  ts("2026-07-16T08:35:54Z"),
			Updated:  ts("2026-07-16T14:48:11Z"),
			Closed:   ts("2026-07-16T14:48:11Z"),
			Body:     "# vista: Board view — kanban DnD（pragmatic-drag-and-drop）+ blocked 旗\n\n- 列 = lane（`furrow board` の語彙、ハードコードしない）。\n- cross-column drag = lane 変更、within-column drag = priority 書き換え（Linear の「手動順序は1つの正準順序」= furrow の sparse int priority そのもの）。**furrow 側の相対 reorder／set --priority（dep 参照）で 1 write に**。\n- card = title + id + value/effort pips + label dots + repo 略記。display options で toggle。\n- **blocked card に旗 + dim**（最安・最高価値の依存可視化）。parent は card ネストにしない。\n- optimistic update・スピナー無し（local data）。DnD は `@atlaskit/pragmatic-drag-and-drop` v2（dnd-kit classic は凍結済み、調査 2026-07）。\n\n2026-07-16: furrow 側の依存 2/3 が done — t-phgp（furrow#142 reorder --before/--after）と t-ecfm（furrow#143 set -s --before/--after）。DnD 用 CLI write プリミティブは main に揃ったが未リリース（最新 release は v0.10.0）— vista から使うには次の furrow release か source build が必要。残る依存は t-g8bn（FurrowPort/adapter）。\n\n2026-07-16 追記: v0.11.0 release 済み — DnD write プリミティブ（reorder/set の相対指定）と boards が released binary で使える。furrow 側の前提は全部出荷済み。残依存は t-g8bn (FurrowPort/adapter) のみ。\n\nReconciled 2026-07-16: dep t-g8bn (FurrowPort/adapter + TanStack Query) done — vista#5 merged。t-g8bn の引き継ぎメモどおり本 task が次着手候補。ただし furrow 側ギャップ t-phgp (reorder --before/--after)・t-ecfm が先行との記載あり — 着手時に要確認。\n- 🚧 `vista#6` opened\n\n2026-07-16 セッション進捗（PR: https://github.com/akira-toriyama/vista/pull/6 ）\n\n- [x] FurrowPort: reorderTask + SetTaskPatch.placement（reorder/set --before/--after への写像）+ MutationReport.renumbered\n- [x] contract test: 実 furrow で reorder 相対配置・atomic respace（renumbered）・set の lane+位置 1 write・lane 跨ぎ reorder=validation\n- [x] domain/kanban: columnize / planDrop（drop 1回=1 write、位置不変=no write）/ optimisticPriority — 全て純関数・TDD\n- [x] application: useDropTask（楽観更新・error rollback・settle refetch）\n- [x] ui/views/board: BoardView/BoardColumn/TaskCard（pragmatic-drag-and-drop v2 + closest-edge、blocked 旗+dim、表示オプション ID/Pips/Labels/Repo、writable=false で read-only）\n- [x] lint/typecheck/99 unit + 24 contract/build 全 green\n- [x] GUI 描画は scratch board（XDG_CONFIG_HOME 差し替え）で実機確認 ✓\n- [ ] native drag の e2e 検証 → [[t-q6rc]]（Tart VM。ホストの mouse 自動操作は禁止＝ユーザー指示）\n\n\n… (truncated in the POC fixture)",
		},
	}
}
